spring:
  application:
    name: SpringMonitoring
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:spring-monitoring
    username: sa
    password:
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      properties:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        generate_statistics: true
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'